# Generated by Django 3.2.9 on 2022-04-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
