# Generated by Django 3.2.9 on 2022-02-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
