# Generated by Django 3.2.9 on 2022-02-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_companyprofile_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='category',
        ),
    ]
