# Generated by Django 3.2.9 on 2022-02-10 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_remove_companyprofile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='likes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
