# Generated by Django 3.2.9 on 2022-02-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_companyprofile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='likes',
        ),
    ]
