# Generated by Django 3.2.9 on 2022-02-11 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_companyprofile_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^(\\+98|0)?9\\d{9}$')]),
        ),
    ]
