# Generated by Django 3.2.9 on 2022-02-13 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20220211_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='home_phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n01712345678', regex='^(\\+98|0)?\\d{10}$')]),
        ),
    ]
