# Generated by Django 3.2.9 on 2022-02-17 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_companyprofile_home_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
