# Generated by Django 3.2.9 on 2022-02-25 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20220218_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='home_phone_number',
            field=models.CharField(default=None, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n01712345678', regex='^(\\+98|0)?\\d{10}$')], verbose_name='شماره تلفن شرکت'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(default=None, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'مرد'), ('FEMALE', 'زن')], max_length=25, null=True, verbose_name='جنسیت'),
        ),
    ]
