# Generated by Django 3.2.9 on 2022-05-12 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_watchlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name': 'علاقه مند', 'verbose_name_plural': 'علاقه مند ها'},
        ),
    ]
