# Generated by Django 3.2.9 on 2022-05-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20220515_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='body',
            field=models.TextField(verbose_name='نوضیحات'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='معرفی'),
        ),
    ]
