# Generated by Django 3.2.9 on 2022-01-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20220102_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='this_address',
            field=models.BooleanField(default=False),
        ),
    ]
