# Generated by Django 3.2.9 on 2022-02-10 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_alter_address_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^09\\d{9}$'), django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^+989\\d{9}$')]),
        ),
    ]
