# Generated by Django 3.2.9 on 2022-02-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_alter_address_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
