# Generated by Django 3.2.9 on 2022-02-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_alter_address_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ManyToManyField(to='item.ColorItem'),
        ),
    ]
