# Generated by Django 3.2.9 on 2022-02-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_item_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='item.Uploadimage'),
        ),
    ]
