# Generated by Django 3.2.9 on 2022-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20220216_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='item_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
