# Generated by Django 3.2.9 on 2022-02-17 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20220217_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
