# Generated by Django 3.2.9 on 2022-02-17 19:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_auto_20220217_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
