# Generated by Django 3.2.9 on 2022-02-18 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_auto_20220218_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='شماره وارد شده اشتباه است\n09123456789', regex='^(\\+98|0)?9\\d{9}$')], verbose_name='شماره موبایل'),
        ),
    ]
