# Generated by Django 3.2.9 on 2022-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_auto_20220221_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['date'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر'), ('d', 'پیش نویس')], default='d', max_length=10, verbose_name='وضعيت'),
        ),
    ]
